# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='anonymity',
            field=models.BooleanField(default=False),
        ),
    ]
